[config]
default_to_workspace = false

[tasks.sqlx-offline]
command = "cargo"
args = ["sqlx", "prepare", "--workspace"]

[tasks.upgrade]
dependencies = ["upgrade-internal", "update"]

[tasks.upgrade-internal]
command = "cargo"
args = ["upgrade", "-i", "-v"]

[tasks.update]
command = "cargo"
args = ["update"]
