[package]
name = "config"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
dotenvy.workspace = true
object_store.workspace = true

[lints]
workspace = true
