[package]
name = "ml_model"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
feature_extractor.workspace = true

anyhow.workspace = true
burn.workspace = true
memmap2.workspace = true
tracing.workspace = true
uuid.workspace = true
