[package]
name = "project_exe"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# Internal dependencies
database.workspace = true

# External dependencies
anyhow.workspace = true
sqlx.workspace = true
tokio.workspace = true
